=== luisc7/LM2/tagsDiferentes/biblioteca2.dtd
<!ELEMENT biblioteca (libro|revista|periodico)*>
<!ELEMENT libro (titulo-libro, indice-libro, capitulo-libro+, sinopsis)>
<!ATTLIST libro Id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>
<!ATTLIST libro num_pags NMTOKEN #REQUIRED>
<!ELEMENT titulo-libro (#PCDATA)>
<!ELEMENT indice-libro (#PCDATA)>
<!ELEMENT capitulo-libro (titulo-cap, contenido-cap)>
<!ATTLIST capitulo-libro num_pags NMTOKEN #REQUIRED>
<!ELEMENT titulo-cap (#PCDATA)>
<!ELEMENT contenido-cap EMPTY>
<!ATTLIST contenido-cap info_contenido CDATA #REQUIRED>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT revista (titulo-revista, numero, indice-revista, seccion-revista+)>
<!ATTLIST revista Id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otras) #REQUIRED>
<!ATTLIST revista num_pags NMTOKEN #REQUIRED>
<!ELEMENT titulo-revista (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT indice-revista (#PCDATA)>
<!ELEMENT seccion-revista (titulo-secc, contenido-secc)>
<!ATTLIST seccion-revista num_pags NMTOKEN #REQUIRED>
<!ELEMENT titulo-secc (#PCDATA)>
<!ELEMENT contenido-secc EMPTY>
<!ATTLIST contenido-secc info_contenido CDATA #REQUIRED>
<!ELEMENT periodico (indice-periodico, seccion-periodico+)>
<!ATTLIST periodico Id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional|internacional) #REQUIRED>
<!ATTLIST periodico fecha NMTOKEN #REQUIRED>
<!ELEMENT indice-periodico (#PCDATA)>
<!ELEMENT seccion-periodico (articulo, contenido-arti)>
<!ATTLIST seccion-periodico tipo_seccion (economica|opinion|deportes|nacional|internacional) #REQUIRED>
<!ELEMENT articulo (#PCDATA)>
<!ATTLIST articulo autor NMTOKENS #REQUIRED>
<!ELEMENT contenido-arti EMPTY>
<!ATTLIST contenido-arti info_contenido CDATA #REQUIRED>

=== luisc7/LM2/tagsDiferentes/biblioteca2_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca2.dtd">
<biblioteca>

    <libro Id="L1234" tipo_clase="novela" num_pags="215">
        <titulo-libro>
            Las andanzas de Carla, Carlos y Clara
        </titulo-libro>

        <indice-libro>
            MiIndiceLibro
        </indice-libro>

        <capitulo-libro num_pags="30">
            <titulo-cap>
                Tres primos y un destino
            </titulo-cap>
            <contenido-cap info_contenido="L1234/capitulo-1.html"/>
        </capitulo-libro>

        <capitulo-libro num_pags="35">
            <titulo-cap>
                Tres primos y dos vecinos
            </titulo-cap>
            <contenido-cap info_contenido="L1234/capitulo-2.html"/>
        </capitulo-libro>

        <capitulo-libro num_pags="33">
            <titulo-cap>
                Tres primos y tres bovinos
            </titulo-cap>
            <contenido-cap info_contenido="L1234/capitulo-3.html"/>
        </capitulo-libro>

        <sinopsis>
            Desventuras variadas
        </sinopsis>

    </libro>

    <revista Id="R4567" tipo_clase="coches" num_pags="72">

        <titulo-revista>
            Motor simphony
        </titulo-revista>

        <numero>
            1
        </numero>

        <indice-revista>
            MiIndiceRevista
        </indice-revista>

        <seccion-revista num_pags="12">
            <titulo-secc>
                Pruebas
            </titulo-secc>
            <contenido-secc info_contenido="R4567/pruebas_info.html"/>
        </seccion-revista>

        <seccion-revista num_pags="4">
            <titulo-secc>
                Actualidad
            </titulo-secc>
            <contenido-secc info_contenido="R4567/actualidad_info.html"/>
        </seccion-revista>        

    </revista>

    <periodico Id="P9876" tipo_clase="nacional" fecha="2021-01-15">

        <indice-periodico>
            MiIndicePeriodico
        </indice-periodico>

        <seccion-periodico tipo_seccion="economica">
            <articulo autor="Juntaletras Bocachancla">
                1
            </articulo>
            <contenido-arti info_contenido="P9876/articulo_1_info.html"/>
        </seccion-periodico>

        <seccion-periodico tipo_seccion="deportes">
            <articulo autor="Malmetido Zarandajo">
                2
            </articulo>
            <contenido-arti info_contenido="P9876/articulo_2_info.html"/>
        </seccion-periodico>

    </periodico>

</biblioteca>
